Models/EnumStatusTarefa.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TarefaMVC.Models
{
    public enum EnumStatusTarefa
    {
        Pendente = 0,
        Finalizado = 1
    }
}

Models/ErrorViewModel.cs
namespace TarefaMVC.Models;

public class ErrorViewModel
{
    public string RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Tarefa.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
//using Models.EnumStatusTarefa;

namespace TarefaMVC.Models
{
    public class Tarefa
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public DateTime Data { get; set; }
        public EnumStatusTarefa Status { get; set; }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using TarefaMVC.Models;

namespace TarefaMVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/TarefaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TarefaMVC.Context;
using TarefaMVC.Models;

namespace TarefaMVC.Controllers
{
    public class TarefaController : Controller
    {
        private readonly TarefaContext _context;

        public TarefaController(TarefaContext context){
            _context = context;
        }
        public IActionResult Index(){
            var tarefas = _context.Tarefas.ToList();
            return View(tarefas);
        }
        
        public IActionResult Criar(){
            return View();
        }

        [HttpPost]
        public IActionResult Criar(Tarefa tarefa){
            if(ModelState.IsValid){
                _context.Tarefas.Add(tarefa);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(tarefa);
        }


        public IActionResult Editar(int id){
            var tarefa = _context.Tarefas.Find(id);
            if(tarefa == null)
                return NotFound();
            
            return View(tarefa);
        }

        [HttpPost]
        public IActionResult Editar(Tarefa tarefa){
            var tarefaBanco = _context.Tarefas.Find(tarefa.Id);

            tarefaBanco.Titulo = tarefa.Titulo;
            tarefaBanco.Descricao = tarefa.Descricao;
            tarefaBanco.Data = tarefa.Data;
            tarefaBanco.Status = tarefa.Status;

            _context.Tarefas.Update(tarefaBanco);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Detalhes(int id){
            var tarefa = _context.Tarefas.Find(id);

            if(tarefa == null)
                return RedirectToAction(nameof(Index));

            return View(tarefa);
        }

        public IActionResult Deletar(int id){
            var tarefa = _context.Tarefas.Find(id);

            if(tarefa == null)
                return RedirectToAction(nameof(Index));

            return View(tarefa);
        }

        [HttpPost]
        public IActionResult Deletar(Tarefa tarefa){
            var tarefaBanco = _context.Tarefas.Find(tarefa.Id);

            _context.Tarefas.Remove(tarefaBanco);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TarefaMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TarefaMVC.styles.css" asp-append-version="true" />
    @* <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" /> *@
    <script src="https://kit.fontawesome.com/ea9daa3d8f.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TarefaMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tarefa" asp-action="Index">Tarefa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TarefaMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Tarefa/Criar.cshtml
@model TarefaMVC.Models.Tarefa

@{
    ViewData["Title"] = "Criar Tarefa";
}

<h1>Criar Tarefa</h1>
<hr>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Criar">
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control"/>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control"/>
            </div>
            <div class="form-group">
                <label asp-for="Data" class="control-label"></label>
                <input asp-for="Data" class="form-control"/>
            </div>
            
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control" asp-items="Html.GetEnumSelectList<EnumStatusTarefa>()">
                </select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
           
            <br>            

            <br>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-success" style="width: 80px"/>
                <a asp-action="Index" type="button" class="btn btn-primary" style="width: 80px">Cancelar</a>
            </div>
        </form>
    </div>
</div>
<hr>

Views/Tarefa/Deletar.cshtml
@model TarefaMVC.Models.Tarefa

@{
    ViewData["Title"] = "Deletar";
}

<h1 style="color: red;">Confirme a Exclusão da Terefa</h1>
<hr>

<div>
    <dl class="row"  style="border: 1px solid;">
        <dt class="col-sm-3" style="background-color: lightgrey; border: 1px solid;">
            @* @Html.DisplayNameFor(x => x.Titulo) *@
            TITULO:
        </dt>
        <dt class="col-sm-9" style="border: 1px solid;">
            @Html.DisplayFor(x => x.Titulo)
        </dt>
        <dt class="col-sm-3" style="background-color: lightgrey;border: 1px solid;">
            DESCRIÇÃO:
        </dt>
        <dt class="col-sm-9" style="border: 1px solid;">
            @Html.DisplayFor(x => x.Descricao)
        </dt>
        <dt class="col-sm-3" style="background-color: lightgrey;border: 1px solid;">
            DATA:
        </dt>
        <dt class="col-sm-9" style="border: 1px solid;">
            @Html.DisplayFor(x => x.Data)
        </dt>
        <dt class="col-sm-3" style="background-color: lightgrey;border: 1px solid;">
            STATUS:
        </dt>
        <dt class="col-sm-9" style="border: 1px solid;">
            @Html.DisplayFor(x => x.Status)
        </dt>
    </dl>
</div>

<form asp-action="Deletar">
    <input type="submit" value="Deletar" class="btn btn-danger" style="width: 80px"/>
<a asp-action="Index" type="button" class="btn btn-primary" style="width: 80px">Cancelar</a>
</form>

Views/Tarefa/Detalhes.cshtml
@model TarefaMVC.Models.Tarefa

@{
    ViewData["Title"] = "Detalhes";
}

<h1>Detalhes</h1>

<div>
    <dl class="row"  style="border: 1px solid;">
        <dt class="col-sm-3" style="background-color: lightgrey; border: 1px solid;">
            @* @Html.DisplayNameFor(x => x.Titulo) *@
            TITULO:
        </dt>
        <dt class="col-sm-9" style="border: 1px solid;">
            @Html.DisplayFor(x => x.Titulo)
        </dt>
        <dt class="col-sm-3" style="background-color: lightgrey;border: 1px solid;">
            DESCRIÇÃO:
        </dt>
        <dt class="col-sm-9" style="border: 1px solid;">
            @Html.DisplayFor(x => x.Descricao)
        </dt>
        <dt class="col-sm-3" style="background-color: lightgrey;border: 1px solid;">
            DATA:
        </dt>
        <dt class="col-sm-9" style="border: 1px solid;">
            @Html.DisplayFor(x => x.Data)
        </dt>
        <dt class="col-sm-3" style="background-color: lightgrey;border: 1px solid;">
            STATUS:
        </dt>
        <dt class="col-sm-9" style="border: 1px solid;">
            @Html.DisplayFor(x => x.Status)
        </dt>
    </dl>
</div>
<a asp-action="Editar" asp-route-id="@Model.Id" type="button" class="btn btn-primary">Editar</a>
<a asp-action="Index" type="button" class="btn btn-primary">Voltar</a>

Views/Tarefa/Editar.cshtml
@model TarefaMVC.Models.Tarefa

@{
    ViewData["Title"] = "Editar Tarefa";
}

<h1>Editar Tarefa</h1>
<hr>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Editar">
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control"/>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control"/>
            </div>
            <div class="form-group">
                <label asp-for="Data" class="control-label"></label>
                <input asp-for="Data" class="form-control"/>
            </div>            
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control" asp-items="Html.GetEnumSelectList<EnumStatusTarefa>()">
                </select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>           
            <br>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-success" style="width: 80px"/>
                <a asp-action="Index" type="button" class="btn btn-primary" style="width: 80px">Cancelar</a>
            </div>
        </form>
    </div>
</div>
<hr>

Views/Tarefa/Index.cshtml
@* <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"> *@

@model IEnumerable<TarefaMVC.Models.Tarefa>

@{
    ViewData["Title"] = "Tarefas";
}

<h2>Tarefas</h2>
<p>
    <a asp-action="Criar">Nova Tarefa</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th style="background-color: black; color: white; border-right: 1px solid; border-color: white; text-align: center">COD</th>
            <th style="background-color: black; color: white; border-right: 1px solid; border-color: white; text-align: center">TITULO</th>
            <th style="background-color: black; color: white; border-right: 1px solid; border-color: white; text-align: center">DESCRIÇÃO</th>
            <th style="background-color: black; color: white; border-right: 1px solid; border-color: white; text-align: center">DATA</th>
            <th style="background-color: black; color: white; border-right: 1px solid; border-color: white; text-align: center">STATUS</th>
            <th style="background-color: black; color: white; text-align: center;">AÇÕES</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td style="border: 1px solid; text-align: center">
                    @Html.DisplayFor(model => item.Id)
                </td>
                <td style="border: 1px solid">
                    @Html.DisplayFor(model => item.Titulo)
                </td>
                <td style="border: 1px solid">
                    @Html.DisplayFor(model => item.Descricao)
                </td>
                <td style="border: 1px solid">
                    @Html.DisplayFor(model => item.Data)
                </td>
                <td style="border: 1px solid">
                    @Html.DisplayFor(model => item.Status)
                </td>
                <td style="border: 1px solid; text-align: center">
                    <a asp-action="Editar" asp-route-id="@item.Id" class="fa-solid fa-pen-to-square"></a>&#160
                    <a asp-action="Detalhes" asp-route-id="@item.Id" class="fa-solid fa-circle-info"></a>&#160
                    <a asp-action="Deletar" asp-route-id="@item.Id" class="fa-solid fa-trash-can"></a>
                </td>
            </tr>
        }
    </tbody>
</table>